Problem - 1: Array Creation:

In [ ]:
import numpy as np

In [ ]:
# 1

array_empty = np.empty((2,2))
array_empty

array([[1.97303348e-315, 0.00000000e+000],
       [4.69362364e-322, 2.30955689e+161]])

In [ ]:
# 2

ones_array = np.ones((4,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# 3

given_shape = (3, 5)
filled_array = np.full(given_shape, 2, dtype=float)
filled_array

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [ ]:
# 4

given_shape = (3, 5)
array_zeros = np.zeros(given_shape, dtype=float)
array_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 5

given_shape = (3, 5)
array_ones = np.ones(given_shape, dtype=float)
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 6

new_list = [1,2,3,4]
converted_new_list = np.array(new_list)
converted_new_list

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# 1

values = np.arange(10, 50)
values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# 2

zero_to_eight = np.arange(0, 9)
zero_to_eight_2 = zero_to_eight.reshape(3, 3)
zero_to_eight_2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 3

identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 4

random_array = np.random.random(30)
mean = random_array.mean()
print("Mean =", mean.item())

Mean = 0.49604791699809175


In [ ]:
# 5

array = np.random.random((10, 10))
minimum = array.min()
maximum = array.max()

print("Minimum value:", minimum)
print("Maximum value:", maximum)

Minimum value: 0.01485778208606392
Maximum value: 0.9865649168133435


In [ ]:
# 6

zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
# 8

array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 9

pattern = np.zeros((8,8))
pattern[1::2, ::2] = 1
pattern[::2, 1::2] = 1
pattern

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem - 3: Array Operations:

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [ ]:
# 1

addition = x + y
addition

array([[ 6,  8],
       [10, 13]])

In [ ]:
# 2

subtraction = w - v
subtraction

array([2, 2])

In [ ]:
# 3

multiply = y * 5
multiply

array([[25, 30],
       [35, 40]])

In [ ]:
# 4

square = y ** 2
square

array([[25, 36],
       [49, 64]])

In [ ]:
# 5

dot_vw = np.dot(v, w)
print("Dot product between v(and)w = ", dot_vw)
dot_xv = np.dot(x, v)
print("Dot product between x(and)v = ", dot_xv)
dot_xy = np.dot(x, y)
print("Dot product between x(and)y = \n", dot_xy)

Dot product between v(and)w =  219
Dot product between x(and)v =  [29 77]
Dot product between x(and)y = 
 [[19 22]
 [50 58]]


In [ ]:
# 6

concatenate1 = np.concatenate((x, y))
print("x(and)y along row:\n", concatenate1)

concatenate2 = np.column_stack((v, w))
print("v(and)w along column:\n", concatenate2)

x(and)y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v(and)w along column:
 [[ 9 11]
 [10 12]]


In [ ]:
# 7

np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Here we get an error because x has shape (2,2) so it is a 2 dimensional array but v has shape (2,) so it is a 1 dimensional array. Hence, they cannot be concatenated unless they both have same dimensionality.

Probem - 4: Matrix Operations:

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
# 1.1

A_inv = np.linalg.inv(A)
result = A @ A_inv
result = np.round(result).astype(int)

identity = np.eye(2, dtype = int)

print("A * A^-1 =\n", result, "\nI =\n", identity)
if (np.array_equal(result, identity)):
  print("A * A^-1 = I")

A * A^-1 =
 [[1 0]
 [0 1]] 
I =
 [[1 0]
 [0 1]]
A * A^-1 = I


In [ ]:
# 1.2

AB = A @ B
BA = B @ A

print("AB =\n", AB, "\nBA =\n", BA)

print("A * B = B * A:", np.array_equal(AB, BA))

AB =
 [[23 13]
 [51 29]] 
BA =
 [[36 44]
 [13 16]]
A * B = B * A: False


In [ ]:
# 1.3

LHS = (A @ B).T
RHS = B.T @ A.T

print("LHS =\n", LHS, "\nRHS =\n", RHS)
if (np.array_equal(LHS, RHS)):
  print("(A.B)T (LHS) = (B)T.(A)T (RHS)")

LHS =
 [[23 51]
 [13 29]] 
RHS =
 [[23 51]
 [13 29]]
(A.B)T (LHS) = (B)T.(A)T (RHS)


In [ ]:
# 2

"""
Equations:
2x - 3y + z = -1
 x - y + 2z = -3
3x + y -  z =  9

"""

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]], dtype=float)

B = np.array([-1, -3, 9], dtype=float)

# AX = B
# X = A^-1 . B
# Finding X using np.linalg.inv()

A_inverse = np.linalg.inv(A)
X = A_inverse @ B
print("Solving using inverse matrix method:\n", X)

Solving using inverse matrix method:
 [ 2.  1. -2.]


In [ ]:
# 3

# Finding X using np.linalg.solve()
X_solve = np.linalg.solve(A, B)
print("Solving using np.linalg.sovle():\n", X_solve)

Solving using np.linalg.sovle():
 [ 2.  1. -2.]


Experiment:

In [ ]:
import time

# python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# numpy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

In [ ]:
# 1

# python lists

start = time.time()
list_add = [list1[i] + list2[i] for i in range(1000000)]
end = time.time()
print("Time for elementwise addition of python lists:", end - start, "s")

# numpy arrays

start = time.time()
array_add = array1 + array2
end = time.time()

print("Time for elementwise addition of numpy arrays:", end - start, "s")

Time for elementwise addition of python lists: 0.15311765670776367 s
Time for elementwise addition of numpy arrays: 0.002329587936401367 s


In [ ]:
# 2

# python lists

start = time.time()
list_multiply = [list1[i] * list2[i] for i in range(1000000)]
end = time.time()
print("Time for elementwise multiplication of python lists:", end - start, "s")

# numpy arrays

start = time.time()
array_multiply = array1 * array2
end = time.time()

print("Time for elementwise multiplication of numpy arrays:", end - start, "s")

Time for elementwise multiplication of python lists: 0.16138505935668945 s
Time for elementwise multiplication of numpy arrays: 0.002824544906616211 s


In [ ]:
# 3

# python lists

start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(1000000))
end = time.time()
print("Time for dot product of python lists:", end - start, "s")

# numpy arrays

start = time.time()
array_dot = np.dot(array1, array2)
end = time.time()

print("Time for dot product of numpy arrays:", end - start, "s")

Time for dot product of python lists: 0.22738051414489746 s
Time for dot product of numpy arrays: 0.0029993057250976562 s


In [70]:
# 4

# python matrices
python1 = [[1 for _ in range(1000)] for _ in range(1000)]
python2 = [[1 for _ in range(1000)] for _ in range(1000)]

start = time.time()
python3 = [[sum(python1[i][k] * python2[k][j] for k in range(1000))
           for j in range(1000)] for i in range(1000)]
end = time.time()

print("Time for python matrix multiplication:", end - start, "s")

# numpy matrices
np1 = np.ones((1000, 1000))
np2 = np.ones((1000, 1000))

start = time.time()
np3 = np1 @ np2
end = time.time()

print("Time for numpy matrix multiplication:", end - start, "s")

Time for python matrix multiplication: 125.24725317955017 s
Time for numpy matrix multiplication: 0.0767977237701416 s
